### PR TITLE
Utility class to parse access token.

### PR DESCRIPTION
**Pull request by FeiChen-okta**
#### Description:
Parse an access token and return OktaAccessToken.

#### Testing details:
- [x]  Verified basic functionality of change
- [x]  Added tests 

##### RESOLVES: 
[OKTA-246596](https://oktainc.atlassian.net/browse/OKTA-246596)

### CODE REVIEW

**Comment by IldarAbdullin-okta** [comment]
Why we can't use jwt-java sdk? https://github.com/okta/okta-jwt-verifier-java

**Comment by FeiChen-okta** [comment]
> Why we can't use jwt-java sdk? https://github.com/okta/okta-jwt-verifier-java

It depends on other libraries and those haven't been tested on android. The pom.xml file:
https://github.com/okta/okta-jwt-verifier-java/blob/master/impl/pom.xml

**Comment by IldarAbdullin-okta** [comment]
> > Why we can't use jwt-java sdk? https://github.com/okta/okta-jwt-verifier-java
> 
> It depends on other libraries and those haven't been tested on android. The pom.xml file:
> https://github.com/okta/okta-jwt-verifier-java/blob/master/impl/pom.xml

Any other open-source android libs?

**Comment by hansreichenbach-okta** [comment]
we use jjwt internally and it does good work https://github.com/jwtk/jjwt

**Comment by FeiChen-okta** [comment]
Not needed. Token is parsed in application layer.

**Pull request closed without merging**
